import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "./components/Navbar";
import { ReactTyped } from "react-typed";
import * as motion from 'motion/react-client';
import Footer from "./components/Footer";
import { useRouter } from 'next/router';
import { useAuth } from "@/context/AuthContext";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const router = useRouter();
  const {user} = useAuth();

  useEffect( ()=>{
     
    const getUser = async ()=>{
      if(user){
        console.log("here");
        const [userDataResponse] = await Promise.all([
          fetch(`/api/users/getuser?userUID=${user.uid}`),
        ]);
        const userData = await userDataResponse.json();
        if(userDataResponse.ok && user){
            router.push("/research/hello");
        }else{
          router.push("/SignUp");
        } 
      }
    }
    getUser();
   
    // const interval = setInterval(()=>{
    //     setTextIndex((prevIndex)=> {
    //       if(prevIndex + 1 < texts.length){
    //         return prevIndex + 1;
    //       }else{
    //         return 0;
    //       }
    //     });
    // },2000);
    // return ()=> clearInterval(interval)

   
  },[]);


  return (
    <>
        <Head>
          <title>Vakeel Ai</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />

          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
          <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Istok+Web:ital,wght@0,400;0,700;1,400;1,700&family=Joan&display=swap" rel="stylesheet"></link>
        </Head>
          <>
              <div className={`${styles.hero_page}`}> 
                  <Navbar/>
                  <main className={styles.main}>
                    <motion.div   
                    // initial={{ opacity: 0, scale: 0.8, y: 50 }} // Start slightly smaller and lower
                    //   whileInView={{ opacity: 1, scale: 1, y: 1 }} // Pop up to normal size
                    //   transition={{ duration: 1.2, ease: "easeOut" }} // Control the speed and smoothness 
                      className={styles.main_content}>
                          <div className={styles.main_content_left}>
                                <div className={styles.main_logo_container}>
                                      <img src="/advocate.png" width={60} height={80}/>
                                      <h2 className={styles.main_logo_header}>Vakeel Ai</h2>
                                </div>
                                <h2 className={styles.main_sub_header}>democratising law <br/> knowledge & 🔍 research </h2>

                                <div className={styles.main_action_button} onClick={() => router.push('/SignUp')}>
                                    <p className={styles.main_action_button_text}>Try Now</p>
                                </div>
                            
                          </div>
                          <div className={styles.main_content_right}>

                                <div className={styles.main_image_container}>
                                    <img className={styles.phone_image} src="/phone.png" width={50} height={100}/>
                                </div>
                          </div>
                    </motion.div>
                  </main>
              </div>

              <div className={styles.features_page}>
                    <h2 className={styles.features_page_header}>Features like  no place else!</h2>
                    <div className={styles.feature_div}>
                        <div className={styles.feature_div_left}>
                            <h2 className={styles.feature_div_header}>
                              Deep Legal <br/> Research
                            </h2>
                            <p className={styles.feature_div_description}>
                               Search through lakhs of real court judgments across the Supreme Court, High Courts, and District Courts.
                            </p>
                        </div>
                        <div className={`${styles.feature_div_right} ${styles.feature_image_one} `}>
                            <h2 className={styles.feature_div_logo}>🔍 Search</h2>
                        </div>
                    </div>



                    <div className={styles.feature_div_two}>
                       
                        <div className={`${styles.feature_div_two_left} ${styles.feature_image_two} `}>
                           <img src="/contract.png" width={95} height={95}/>
                        </div>
                        <div className={styles.feature_div_two_right}>
                            <h2 className={styles.feature_div_header}>
                              AI Case <br/> Summaries
                            </h2>
                            <p className={styles.feature_div_description}>
                              No more legal jargon. <br/> Easy to understand summaries tailored for lawyers & common man. 
                            </p>
                        </div>
                    </div>

                    <div className={styles.feature_div}>
                        <div className={styles.feature_div_left}>
                            <h2 className={styles.feature_div_header}>
                              Ask questions in <br/> Simple language
                            </h2>
                            <p className={styles.feature_div_description}>
                              “a case of couples fighting”
                            </p>
                        </div>
                        <div className={`${styles.feature_div_right} ${styles.feature_image_three} `}>
                            <h2 className={styles.feature_div_logo}>🙋</h2>
                        </div>
                    </div>

                    <div className={styles.feature_div_two}>
                       
                       <div className={`${styles.feature_div_two_left} ${styles.feature_image_four} `}>
                          <h2 className={styles.feature_div_logo}>📁</h2>
                       </div>
                       <div className={styles.feature_div_two_right}>
                           <h2 className={styles.feature_div_header}>
                              Auto Generated <br/> Case Notes
                           </h2>
                           <p className={styles.feature_div_description}>
                             No more legal jargon. <br/> Easy to understand summaries tailored for lawyers & common man. 
                           </p>
                       </div>
                   </div>

                   <Footer/>
              </div>
             

              


          </>
    </>
  );
}
